## NumPy 总结


- `np.array()` 用于创建向量，矩阵， 整体运算（区别List)；
- `shape` 表示数组形状(几行几列）,`ndim` 表示数组维度；
- `reshape()` 用于改变数组形状， -1自适应；
- 索引和切片可以取出数组中的部分数据；
- 广播机制可以让不同形状的数组进行运算, 低维扩高维；
- `@` 可以进行矩阵乘法；
- `mean()`、`std()`、`max()`、`min()` 是常用统计函数。


In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 1.26.4


In [2]:
# 从 Python 列表创建 NumPy 数组
a = np.array([1, 2, 3, 4, 5])

print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
random_array = np.random.randn(4, 5)

print("zeros:")
print(zeros)

print("ones:")
print(ones)

print("random_array:")
print(random_array)

zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones:
[[1. 1. 1.]
 [1. 1. 1.]]
random_array:
[[ 0.92281171 -0.07599368 -2.23793285  1.02770631  0.64496763]
 [-1.31448466 -1.13817751  1.15611288 -0.55247967  0.51523987]
 [ 1.43933792 -1.17594272  1.92131826  0.12574382 -2.0930298 ]
 [-0.49775029 -2.24445433 -1.31027437  1.63081456 -0.71475322]]


In [4]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("x:")
print(x)

print("shape:", x.shape)
print("dtype:", x.dtype)
print("维度数量:", x.ndim)

x:
[[1 2 3]
 [4 5 6]]
shape: (2, 3)
dtype: int32
维度数量: 2


In [6]:
x = np.arange(12)

print("原始 x:")
print(x)
print("原始 shape:", x.shape)

x_reshaped = x.reshape(3, 4)

print("reshape 之后:")
print(x_reshaped)
print("新的 shape:", x_reshaped.shape)

原始 x:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
原始 shape: (12,)
reshape 之后:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
新的 shape: (3, 4)


In [7]:
x = np.arange(12).reshape(3, 4)

print("x:")
print(x)

print("第 0 行:")
print(x[0])

print("第 1 列:")
print(x[:, 1])

print("前两行，前两列:")
print(x[:2, :2])

x:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
第 0 行:
[0 1 2 3]
第 1 列:
[1 5 9]
前两行，前两列:
[[0 1]
 [4 5]]


In [8]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("原始 x:")
print(x)

print("x + 10:")
print(x + 10)

y = np.array([10, 20, 30])

print("x + y:")
print(x + y)

原始 x:
[[1 2 3]
 [4 5 6]]
x + 10:
[[11 12 13]
 [14 15 16]]
x + y:
[[11 22 33]
 [14 25 36]]


In [9]:
A = np.random.randn(3, 4)
B = np.random.randn(4, 2)

C = A @ B

print("A shape:", A.shape)
print("B shape:", B.shape)
print("C shape:", C.shape)

print("C:")
print(C)

A shape: (3, 4)
B shape: (4, 2)
C shape: (3, 2)
C:
[[ 1.68332335  0.58613731]
 [-1.89864334 -0.02581795]
 [-1.24649282  0.69107132]]


In [10]:
data = np.random.randn(100)

print("均值 mean:", data.mean())
print("标准差 std:", data.std())
print("最大值 max:", data.max())
print("最小值 min:", data.min())
print("中位数 median:", np.median(data))

均值 mean: -0.018038118790113144
标准差 std: 0.9981544570168868
最大值 max: 2.3969270153315327
最小值 min: -3.11125529545367
中位数 median: -0.0819687288115867


In [11]:
scores = np.array([60, 70, 80, 90, 100])

normalized_scores = (scores - scores.min()) / (scores.max() - scores.min())

print("原始分数:")
print(scores)

print("归一化之后:")
print(normalized_scores)

原始分数:
[ 60  70  80  90 100]
归一化之后:
[0.   0.25 0.5  0.75 1.  ]


In [12]:
epochs = np.arange(1, 11)
loss = np.exp(-epochs / 3) + np.random.randn(10) * 0.02

print("epochs:")
print(epochs)

print("loss:")
print(loss)

epochs:
[ 1  2  3  4  5  6  7  8  9 10]
loss:
[0.72017356 0.4688539  0.33862316 0.2861047  0.18635437 0.12375815
 0.11971113 0.0535299  0.05327303 0.00522262]
